### ISSUE TITLE
絵文字の正規表現に Unicode Property Escapes を使う

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/mfm.js#119]
軽くなる

**Comment by syuilo** [comment]
- `Emoji` はただの数字も含まれる、
- `Emoji_Presentation` は`❤️`や`0️⃣`のような一部の絵文字が含まれない、
- `Extended_Pictographic` は`❤️`を含むけど`0️⃣`などは依然含まれない

**Comment by syuilo** [comment]
https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B:Emoji=Yes:%5D

`Emoji`かどうか判定しつつ0-9ではないかチェックすれば良いかも？

**Comment by marihachi** [comment]
よく分からないけどtwemojiの正規表現を置き換えるということ？

**Comment by syuilo** [comment]
yes

**Comment by marihachi** [comment]
正直、絵文字のセットがどういう感じになってるのかぼくはよく分からないので、絵文字エンジニアが必要そう

**Comment by mei23** [comment]
Unicode Emojiパターンは、Twemojiで使える絵文字 (Misskeyで使用しているTwemoji) と一致させる必要がある。
Unicode Property Escapesは、ブラウザによって対応Unicodeバージョンが違いそう。
だからまず無理だと思うのだわ。
