### ISSUE TITLE
リポジトリ名をmfm.jsにしたい

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/mfm.js#30]
特に拘りがなければ、分かりやすさのためそうしたい

**Comment by syuilo** [comment]
ライブラリ名というかリポジトリ名だな

**Comment by syuilo** [comment]
理由としては、将来的にはjs以外の言語でもMFMパーサー用意するかもしれないので、jsを明示しておきたい

**Comment by marihachi** [comment]
リポジトリ名: mfm.js
パッケージ名: mfm-js
にする？

**Comment by syuilo** [comment]
パッケージ名 mfm にできないかな(すでに使われてるかも)

**Comment by syuilo** [comment]
`@misskey-dev/mfm`にする手もある

**Comment by marihachi** [comment]
パッケージ名 `mfm` はもう使われてた。
`@misskey-dev/mfm` は手打ちするには長い気がするなあ。

- `mfmjs`
- `mfm-js`
- `misskey-markdown`
- `misskey-mfm`

他にあるかな

**Comment by syuilo** [comment]
mfm-jsかなあ

**Comment by marihachi** [comment]
パッケージ名はmfm-jsでいくか

**Comment by marihachi** [comment]
リポジトリ名は変更完了

**Comment by marihachi** [comment]
ok
