### ISSUE TITLE
textルールはStringリテラルとして返すように

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/mfm.js#32]
パフォーマンス改善
リテラルを後から結合してテキストノードを生成する

branch: https://github.com/misskey-dev/mfm.js/tree/work-32

**Comment by syuilo** [comment]
後からじゃなくてパースの段階で結合することってできないのかな

**Comment by syuilo** [comment]
https://github.com/misskey-dev/mfm.js/blob/ae2296d6e1d606abcc2529f98852cccbb7d819d0/src/parser.pegjs#L389
を`.+`にしたらダメなのかな

**Comment by marihachi** [comment]
連続にしちゃうと他の構文とマッチする可能性があるからできない

**Comment by marihachi** [comment]
肯定先読み`&`でその文字が他の構文とマッチするかどうかを確認することもできるけど、
これをすると計算量がかなり増えると思うのでやらない

**Comment by marihachi** [comment]
完了
