### ISSUE TITLE
emojiノードの改善

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/mfm.js#36]
カスタム絵文字とUnicode絵文字をより扱いやすくする

**Comment by syuilo** [comment]
(今のMisskeyでは事情により実装されてないけど)`:foo:`形式の構文は、実はカスタム絵文字だけじゃなくてUnicode絵文字も指定することができる(例えば`:+1:`)ので、typeはcustomEmojiとかじゃなくてemojiCodeとかにする必要がありそう

**Comment by marihachi** [comment]
知らなかった
emojiCodeにする方が良いね

**Comment by marihachi** [comment]
調べたら、Emoji Shortcodesっていう名前があるらしい

**Comment by marihachi** [comment]
修正終わった
