### ISSUE TITLE
ブランチ運用・リリースの仕方

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/mfm.js#40]
将来的にはStable版とCanary版をnpmにリリースしていきたい。

- Canary版: テスト向け。ガンガン機能追加・変更してテストするためのリリース。
- Stable版: ユーザー向けのリリース。

普通どんな感じでブランチの運用とかリリースをするんだろう。
うまくGitHub Actionsも使えると管理が楽そう

**Comment by marihachi** [comment]
ブランチ構成はこんな感じ？
- `work/*` : 機能追加・改善の作業用
- `develop` : 雑多な変更、workブランチのマージ先
- `release/dev` : Dev版リリース用
- `release/stable` : Stable版リリース用

**Comment by marihachi** [comment]
Stable版は今までと変わらずこんな感じで良いか 
1. developでバージョン(package.json)を更新
2. developをmasterにマージ
3. master上でリリースタグを付けてパッケージをpublish

**Comment by syuilo** [comment]
git flowか

**Comment by marihachi** [comment]
git flowっぽいけどhotfixとかreleaseブランチは使わなくて良いと思う
早急に直さないといけない状況ってなさそうだし、developかdevelopの派生ブランチで修正してリリースすれば十分そう

**Comment by marihachi** [comment]
misskey-devのnpm orgを作って[パッケージ](https://www.npmjs.com/package/mfm-js)のPublishの権限を与えることってできるかな
個人のトークンを使わないほうが良さそうな気がするし
