### ISSUE TITLE
ハッシュタグの検出を改良する

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/mfm.js#43]
```
C#​の後ろに来る文章がハッシュタグとして認識されないようにするにはどうするべきか…
```
のように、途中にナンバーサインを含むキーワードがあるとそれ以降すべてハッシュタグだと認識されてしまうので、何らかの改良をしたい

案としては、ナンバーサインの前に改行またはスペースを必要にするというのはどうだろう

**Comment by marihachi** [comment]
良さそう

**Comment by marihachi** [comment]
書いてみた #44
