### ISSUE TITLE
メンションの判定の改良

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/mfm.js#45]
https://github.com/misskey-dev/mfm.js/issues/43 と同じ
例えば`syuilotan@yahoo.co.jp`のような文字列もメンションと判定されてしまう

**Comment by marihachi** [comment]
:pray: 
7f353dab5175b84d7c93dbaadd596a5b1624d679

**Comment by syuilo** [comment]
改行やスペースが無くても
```
あいう@fooえお
```
はメンションと判定されて欲しい(`@`の直前が`[a-zA-Z]`以外なら判定されて欲しい)

**Comment by marihachi** [comment]
naruhodo

**Comment by syuilo** [comment]
YOSASOU

**Comment by marihachi** [comment]
https://github.com/misskey-dev/mfm.js/commit/e0f78290ef7d14a76a3917efb482b00f37b18408 
修正

**Comment by syuilo** [comment]
hayai

**Comment by marihachi** [comment]
聞きつつもう変えてた
