### ISSUE TITLE
ネストされた構文の負荷が高い

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/mfm.js#49]
https://github.com/misskey-dev/mfm.js/issues/48#issuecomment-821927829
> 破壊的変更になるので、しばらくは新旧両方の構文をサポートすることが望ましい

時期をみて旧構文を廃止する

**Comment by syuilo** [comment]
> しばらくは新旧両方の構文をサポートすることが望ましい

と思ってたけど、何重にもした旧関数構文を含むノートを投稿すると、ReDoSのように簡単にサーバーにものすごい負荷をかけることが出来るので、早めに切った方が良いかもしれない

**Comment by syuilo** [comment]
これに起因してサーバーが落ちる事象が多数確認されているので、優先度高めで対処したい

**Comment by futchitwo** [comment]
個人的にはネストできなくなってもいいから後方互換のために旧構文残してほしい気持ち…

**Comment by marihachi** [comment]
そもそもこの高負荷は、
ネストされた関数の開始部分`[fn [fn`はそのままリンクラベルにリンクがネストされている状態(リンク開始"["+テキスト"fn "+リンク開始"[")としても解釈可能で(リンク`[...](...)`にマッチはしないけど)、優先度もリンクラベルのほうが高いため、まずリンクとして処理しようとして失敗し、最終的には関数として処理される → 「括弧を含んだリンクラベル+ネストされた関数」の処理時間が掛かる。
っていうのが原因になってる。

つまり、旧関数を廃止してもパーサは`[fn [fn [fn [fn [fn [fn`をリンクラベルとして解釈しようとするんだよね。
旧関数とリンクラベルがどのくらいの割合で負荷を高めてるかわからないけど、両方が関係してる。

**Comment by marihachi** [comment]
ネストされすぎるとV8が落ちるっぽい
スタックオーバーフロー？

**Comment by marihachi** [comment]
応急処置としてリンクラベル内のリンクのネストとMFM関数(両方)を無効にしても良い？

**Comment by marihachi** [comment]
misskeyが落ちたり負荷が高すぎる問題は回避できると思う

**Comment by syuilo** [comment]
> 応急処置としてリンクラベル内のリンクのネストとMFM関数(両方)を無効にしても良い？

LGTM

**Comment by marihachi** [comment]
リンクラベルのルールがマズくて負荷がかかってると分かってきた

**Comment by marihachi** [comment]
やっぱ全般的にネストがダメっぽい雰囲気

**Comment by marihachi** [comment]
再帰処理を含む重そうな処理を無効にしてv0.16.3をリリースした
- MFM関数(v1, v2)のネスト → 無効化
- リンクラベルの中のインライン構文 → PlainParserを適用するように変更
- ハッシュタグに括弧ペアを含められる機能 → 無効化
- URLに括弧ペアを含められる機能 → 無効化

**Comment by marihachi** [comment]
ボトムアップ型のパーサに書き直したい

**Comment by marihachi** [comment]
PEG.jsのキャッシュ機能を使えばネストされた構文の解析を高速化できることが分かった

**Comment by marihachi** [comment]
一旦キャッシュを有効にしてリリースして良いかな？

**Comment by syuilo** [comment]
LGTM

**Comment by marihachi** [comment]
軽くなったのでclose
