### ISSUE TITLE
ネスト回数の制限などの細かい制御を行う

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/mfm.js#56]
## パーサを手書きで実装する？
PEG.jsで宣言的に記述したパーサでは細かい制御ができないため、
再帰下降パーサを手書きして置き換えたい。

実験用ブランチ:
https://github.com/misskey-dev/mfm.js/tree/parser-alt-impl-1 (offsetを自動的に計算したいため実験中止)
https://github.com/misskey-dev/mfm.js/tree/parser-alt-impl-2 (offsetを自動計算できるようになった)

## PEG.jsのプラグインで細かい制御を行う？
PEG.jsのプラグインを作成することで、パーサの動作を細かく制御できる可能性が出てきた。
まずはPEG.jsのプラグインでできることを調査する。
Related to #57 

peg.jsリポジトリ上のドキュメント:
https://github.com/pegjs/pegjs/blob/master/docs/guides/plugins.md 

peg.jsのforkのPeggyにある説明:
https://github.com/peggyjs/peggy#plugins-api 

実験用ブランチ:
https://github.com/misskey-dev/mfm.js/tree/expr-pegjs-plugin-1

**Comment by mei23** [comment]
基本的に、ネスト回数などの制御はrender側で行って、構文パーサーのタスクにしなくていいのではというのがあり。
そもそも以前 (-v11?) は、ネスト回数の制御などはクライアントのrenderで行っていたはずなのでそれでいいのではと。

また、関数構文のパースでは関数名が正しいかはmfm.js側では感知せず、それが有効か自体クライアント次第となっていて
その状況で、ネスト回数の制限とか追加していってもというのがあり。
また、例えば「拡大とアニメーションはネストしていいがアニメーションのネストは不可」みたいな要件があった場合、パーサーでそれ判断しようとすると、どれがアニメーション構文か知ってないといけないというのもあり。

また、どこまで装飾構文を許容するかなどはユーザー設定が絡む可能性があり。(例えば、今では動きのあるMFM～ 設定などがあり)
そこも考えると、細かい制御は構文パーサーではなくてクライアントのrenderで制御いいように思う。

**Comment by marihachi** [comment]
> 基本的に、ネスト回数などの制御はrender側で行って、構文パーサーのタスクにしなくていいのではというのがあり。

これはrender側のパフォーマンスが落ちちゃうなら、render側で必要に応じてネストされている構文をプレーンなテキストに戻せば負荷は減るよね、みたいな話だと思う。

細かい説明を書かなかったのが悪いんだけど、この件は以下のようなデータ入力された場合にパーサ側の負荷が高くなる問題があって、その対策としてパーサ側でネスト回数を制限しようかと進んでいた。
```
[spin [spin [spin [spin [spin [spin [spin [spin [spin [spin [spin [spin [spin [spin 
```

ちなみに、再帰降下パーサにはバックトラックがあって、これがそもそもの高負荷につながっている可能性が高い。
他の解析手法ならこの問題が発生しない可能性がある。(けど開発コストが高そう)

**Comment by marihachi** [comment]
解析手法のパーサが割と楽に書けるなら、それでも全然アリ

**Comment by marihachi** [comment]
あと、PEG.jsのキャッシュ機能を使うようになって、上記のデータが入力がされた場合でもパース時間が大幅に短縮された。
緩和されただけなので、もっと膨大な入力があればまだパフォーマンスが落ちる。

**Comment by marihachi** [comment]
もうあまり問題になってないのでclose

**Comment by marihachi** [comment]
大量にネストするとスタックオーバーフローするっぽいので、やっぱりネスト数の制限はできたほうが良さそう。
深さをカウントする方法でネスト数を制限することに成功したので取り込んで良いかな？
https://github.com/misskey-dev/mfm.js/tree/work/fn-depth-limit

**Comment by syuilo** [comment]
fnだけで大丈夫かな

**Comment by marihachi** [comment]
見てないけどまだ他にもありそう

**Comment by marihachi** [comment]
fn以外でも使えるように、オプション名はfnDepthLimitじゃなくてdepthLimitにするか

**Comment by marihachi** [comment]
inlineにinlineを含むことのできる構文はほとんどネストできそう

**Comment by marihachi** [comment]
こんな感じかな
多い

- bold (inlineを使用)
- small (inlineを使用)
- italic (inlineを使用)
- strike (inlineを使用)
- url (括弧ペアのマッチ)
- link (マッチ条件にinline、url、linkを使用している)
- hashtag (括弧ペアのマッチ)
- mention (マッチ条件に自身を使用)

**Comment by marihachi** [comment]
一通りネスト制限の導入終わったし取り込むか
