### ISSUE TITLE
旧関数構文の廃止

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/mfm.js#59]
関数構文は2種類ある。
構文A: `[fn content]`
構文B: `$[fn content]`

どちらかの構文に統一したほうが良いと思う。
キャッシュ(packrat parsing)のおかげで、構文Aでもそこまで負荷が高くならなくなった。

構文A `[fn content]` の廃止を予定。

Related to #49

**Comment by syuilo** [comment]
パフォーマンス云々抜きにしても、Bの方が衝突を回避できたりサジェスト機能作れるようになったりして便利だからBで良いんじゃないかな

**Comment by marihachi** [comment]
それはあるね
記号がユニークな方が処理しやすい

**Comment by futchitwo** [comment]
サジェストはAでもできるのでは？（例：めいすきー）
実質互換性を取るか処理のしやすさを取るかみたいなところありそう

**Comment by syuilo** [comment]
> サジェストはAでもできるのでは？（例：めいすきー）

`[`はリンク構文でも使われるから、リンク入力しようとするとアニメーションのサジェスト出てくることになって鬱陶しそう

**Comment by mei23** [comment]
> `[`はリンク構文でも使われるから、リンク入力しようとするとアニメーションのサジェスト出てくることになって鬱陶しそう

サジェストが鬱陶しいのは、既存の入力文字列等と被ったりフォーカスを奪ったりするからであって
そこが回避されていれば普通にサジェストを無視して入力が継続できるので
あまり関係ないと思う。

**Comment by marihachi** [comment]
`[fn text]`はリンク`[label](url)`のラベル部分としてもそのまま解釈可能なので、fnだった場合はパースのパフォーマンスが少し落ちると思う。

**Comment by mei23** [comment]
確かに`[`自体出現率高くて遅いので `[fn content]` の方は消したいのはあり。
(parsimmon でも遅い)

**Comment by syuilo** [comment]
そろそろ構文A消しても良さそう(残ってると[こういう](https://github.com/misskey-dev/misskey/issues/7850)問題も出てくる)

**Comment by mei23** [comment]
知らない関数fallbakでくっついちゃうのは別の問題な気がするのだわ

**Comment by marihachi** [comment]
廃止するぞ
