### ISSUE TITLE
関数構文の関数名のホワイトリスト機能

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/mfm.js#62]
オプションから与えた関数名リストに一致した場合のみ受理する

**Comment by marihachi** [comment]
実装してみた

**Comment by syuilo** [comment]
これどういうユースケースで役立ちそうかな

**Comment by marihachi** [comment]
関数構文のパース段階で、返すASTノードとしてfnかtextかを判断できるようになる。存在しない名前の関数がホストアプリに上がることがなくなって、ホストアプリ側で行われてるtextへのフォールバックが不要になる。
