### ISSUE TITLE
b/strong, del などのHTMLに存在するタグの解釈

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/mfm.js#75]
現状`<small>`とか`<i>`くらいしかないけど、b/strong, del もタグとして解釈できて良さそう

**Comment by Johann150** [comment]
`<center>` also already exists. (I think you said `<small>` 2 times by accident?)

I wonder if we should limit to one tag to perform a task. So for example only implement `<b>` but not `<strong>` because they both make text **bold**.

**Comment by Johann150** [comment]
also seems related to #52

**Comment by marihachi** [comment]
タグ形式`<b>`と`<s>`の追加でいいかな？

**Comment by syuilo** [comment]
とりあえずそれでよさそう
